---

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Apt install required system packages.
  apt: pkg={{item}} state=installed
  with_items:
    - zookeeper
    - zookeeperd

- name: Overwrite myid file.
  template: src=myid.j2 dest={{zookeeper_conf_dir}}/conf/myid force="{{ zookeeper_force_myid }}"
  notify:
    - Restart zookeeper

- name: Overwrite default config file
  template: src=zoo.cfg.j2 dest={{zookeeper_conf_dir}}/conf/zoo.cfg
  notify:
  - Restart zookeeper 

- name: Update the log4j config with saner production values
  template: src=log4j.properties.j2 dest={{ zookeeper_conf_dir }}/conf/log4j.properties
  notify:
    - Restart zookeeper

- name: Enable zookeeper service
  service: name=zookeeper enabled=yes
