---
# This playbook deploys the whole application stack in this site.

- name: apply zookeepers configuration 
  hosts: zookeepers
  remote_user: root
  roles:
    - { role: common, when: deploy_zk }
    - { role: zookeeper, when: deploy_zk }

- name: apply masters configuration
  hosts: masters
  remote_user: root
  roles:
    - { role: common, when: deploy_master }
    - { role: master, when: deploy_master }

- name: apply masters configuration
  hosts: slaves
  remote_user: root
  roles:
    - { role: common, when: deploy_slave }
    - { role: slave, when: deploy_slave }
    - { role: gpu, when: deploy_slave }
