---
# This playbook deploys the whole application stack in this site.

- name: Prepare all hosts for Ansible 
  hosts: all
  remote_user: root
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal python-dnspython)
      changed_when: False
  tasks:
   - debug:
      msg: Deploying MESOS
- include: deploy.yml
