---

- name: Reload daemon
  command: systemctl daemon-reload
  when: ansible_service_mgr == 'systemd'

- name: Restart mesos-master
  service: name=mesos-master state=restarted

- name: Restart marathon
  service: name=marathon state=restarted
