---

- name: Install ntp
  apt: name=ntp state=present

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp

- name: Start the ntp service
  service: name=ntp state=started enabled=yes

- name: installing repo for Java 8 in Ubuntu
  apt_repository: repo='ppa:openjdk-r/ppa'

- name: Install Java 8 in Ubuntu (openjdk-8-jdk)
  apt: name=openjdk-8-jdk state=present
  tags: openjdk-8-jdk

- name: Add apt-key
  apt_key: id=E56151BF keyserver=keyserver.ubuntu.com state=present

- name: Add mesosphere repo
  apt_repository: repo='deb http://repos.mesosphere.com/{{ mesos_os_distribution }} {{ mesos_os_distribution_release }} main' state=present update_cache=yes

- name: Install Debian OS packages
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - wget
    - curl
    - unzip
    - python-setuptools
    - python-dev
