---
# This playbook contains common plays that will be run on all nodes.

- name: Install GPU Drivers and packages
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - build-essential 
    - libglu1-mesa 
    - libxi-dev 
    - libxmu-dev 
    - libglu1-mesa-dev
    - nvidia-367
